name: ${name}
main: ${main}
version: ${version}
authors: [ ${ author } ]
api-version: 1.13
runtime-libraries:
  # If not defined, it will be 'libraries'
  # when start with @Plugin: will start with plugin data folder
  libraries-folder: 'libraries'
  repositories:
    - https://maven.aliyun.com/repository/public/
    - https://repo.maven.apache.org/maven2/

  libraries:
    - org.jetbrains.kotlin:kotlin-stdlib-jdk8:${kotlinVersion}
#    - org.jetbrains.kotlin:kotlin-reflect:${kotlinVersion}
#    - org.jetbrains.kotlin:kotlinx-coroutines-core:1.6.4
#    - org.jetbrains.exposed:exposed-core:${exposedVersion}
#    - org.jetbrains.exposed:exposed-dao:${exposedVersion}
#    - org.jetbrains.exposed:exposed-jdbc:${exposedVersion}